---
title: 'Chapter04 연구자-설계 무선 할당 실험'
output: html_notebook
---

1. Stata용 데이터 읽기

```{r setup, include=FALSE}

setwd("D:/Methods-Matter/Rcode/Chapter_04/")
install.packages("foreign")
install.packages("psych")
install.packages("ggplot2")
install.packages("lawstat")
```


```{r}

library(foreign)
library(psych)
library(ggplot2)
library(lawstat)

nyvoucher <- read.dta("../stata_data/ch4_nyvoucher.dta")
attach(nyvoucher)
```


2. 분포 확인하기(그래프)

```{r}
voucher.f <- factor(voucher, levels= c(0,1),
                    labels = c("0 non voucher", "1 voucher"))
v_plot <- ggplot(nyvoucher, aes(x=post_ach, fill=voucher.f, color=voucher.f)) 
v_plot + geom_histogram(binwidth = 5, alpha = 0.25, position="identity")
 
```


3. t-test (동분산성가정: var.equal = TRUE)

```{r}

lawstat::levene.test(post_ach, voucher, location="median")  # levene.test(post_ach, voucher)

t.test(post_ach~voucher, var.equal = TRUE)

```

```{r}
describe(nyvoucher[2:4])
```

```{r}
describeBy(nyvoucher[2:4], group=voucher)
```

4. 회귀분석 (post_ach~voucher)

```{r}
fit_M1 <- lm(post_ach~voucher, data=nyvoucher)
summary(fit_M1)
anova(fit_M1)
confint(fit_M1, level=0.95) # CIs for model parameters
```


5. 회귀분석 (post_ach~voucher+pre_ach)

```{r}
fit_M2 <- lm(post_ach~voucher+pre_ach, data=nyvoucher)
summary(fit_M2)
anova(fit_M2)
confint(fit_M2, level=0.95) # CIs for model parameters
```

