---
title: 'Methods Matter : Rcode 04. investigator-Designed Randomized Experiments'
author: Jong Hoon Kim, PH. D.
date: '2022-01-15'
slug: methods-matter-rcode-04-investigator-designed-randomized-experiments
categories:
  - R
tags:
  - R Markdown
---


1. 필요한 라이브러리 설치

```
 library(foreign) 
 library(psych) 
 library(lawstat) 
 library(ggplot2) 
```


```{r setup, include=FALSE,  }
library(foreign)
library(psych)
library(lawstat)
library(ggplot2)
```

2. STATA 데이터 읽어오기
```{r}
nyvoucher <- read.dta("ch4_nyvoucher.dta")
attach(nyvoucher)
```

3. 분포 확인하기(그래프)

```{r}
voucher.f <- factor(voucher, levels= c(0,1),
                    labels = c("0 non voucher", "1 voucher"))
v_plot <- ggplot(nyvoucher, aes(x=post_ach, fill=voucher.f, color=voucher.f)) 
v_plot + geom_histogram(binwidth = 5, alpha = 0.25, position="identity")
```

4. t-test (동분산성가정: var.equal = TRUE)

```{r}
lawstat::levene.test(post_ach, voucher)
```


```{r}
t.test(post_ach~voucher, var.equal = TRUE)
```

```{r}
describe(nyvoucher[2:4])
```

```{r}
describeBy(nyvoucher[2:4], group=voucher)
```


5. 회귀분석 (post_ach~voucher)

```{r}
fit_M1 <- lm(post_ach~voucher, data=nyvoucher)
summary(fit_M1)
```

```{r}
anova(fit_M1)
```

```{r}
confint(fit_M1, level=0.95) # CIs for model parameters
```

```{r}

```

6. 회귀분석 (post_ach~voucher+pre_ach)

```{r}
fit_M2 <- lm(post_ach~voucher+pre_ach, data=nyvoucher)
summary(fit_M2)
```

```{r}
anova(fit_M2)
```

```{r}
confint(fit_M2, level=0.95) # CIs for model parameters
```



